### ISSUE TITLE
get_signed() throws for non-negative numbers

### ISSUE THREAD

**Issue by narenkn** [taocpp/json#18] opened 2017-12-06 15:08 UTC
Hi,
  I found that get_signed() throws for non-negative numbers. For e.g. the line

`         TEST_ASSERT( custom_from_string( "1" ).get_signed() == 1 );`

throws message as follows

> json: unit test [ custom_from_string( "1" ).get_signed() == 1 ] threw an exception [ invalid json type 'unsigned' ] in line [ 95 ] file [ ../src/test/json/parse.cpp ]

  In my case, I've to use "get_signed()" but the number need not necessarily be a negative number. I think get_signed() should also work for non-negative numbers.

Thanks,
Naren.

**Comment by d-frey** [comment] 2017-12-06 15:16
`get_signed` and `get_unsigned` are low-level accessors and reflect the fact that internally we store signed and unsigned integer values as different types.

If you want to extract a number, you should use `as< ... >()` which forwards to the traits class template. The traits class template is then responsible for how to handle overflows - unchecked casting, check & throw or check & assert... - the default is currently unchecked casting.

This is a duplicate of #16

**Closed by d-frey** 2017-12-06 15:16 UTC
Labels: duplicate, question

**Comment by narenkn** [comment] 2017-12-07 14:12
yep! That works!!
